databases:
  - name: pizzas
    databaseName: pizzas_xe87
    user: pizzas_xe87_user

services:
  - type: web
    name: spacer
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: spacer
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false